### ISSUE TITLE
Failing to build with glibc >2.28?

### ISSUE THREAD

**Issue by jaydcarlson** [OpenNuvoton/NUC970_Buildroot#8]
When Buildroot tries to build package `host-m4-1.4.17` I get this error:
```
fseeko.c: In function 'rpl_fseeko':
/usr/bin/gcc  -I.   -I/home/jay/NUC970_Buildroot/output/host/usr/include  -O2 -I/home/jay/NUC970_Buildroot/output/host/usr/include -c -o vasprintf.o vasprintf.c
fseeko.c:109:4: error: #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
  109 |   #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
      |    ^~~~~
```
This looks similar to this issue:
https://github.com/sifive/freedom-u-sdk/issues/74

I have glibc version `2.29` installed.

**Comment by yachen** [comment]
Hi, 

Please test if attached patch fix this issue.  We don't have working PCs with glibc 2.29 installed. Thanks.


Sincerely,

Yi-An Chen


[0001-Updated-host-m4.zip](https://github.com/OpenNuvoton/NUC970_Buildroot/files/3620884/0001-Updated-host-m4.zip)

**Comment by yachen** [comment]
Hi, Please pull 5f4a6a1, thanks.
